package main
import("encoding/json";"log";"net/http";"os";"strconv";"strings";"time";"github.com/nono-vos/broker/internal/model";"github.com/nono-vos/broker/internal/redaction";"github.com/nono-vos/broker/internal/store")
func main(){s:=store.New(os.Getenv("BROKER_STATE"));if _,ok:=s.GetTarget("demo-web");!ok{_ = s.AddTarget(model.Target{ID:"demo-web",Name:"Demo Web",Origins:[]string{"http://127.0.0.1:4173","http://test-target"}})};mux:=http.NewServeMux()
mux.HandleFunc("/healthz",func(w http.ResponseWriter,r *http.Request){write(w,200,map[string]any{"status":"ok","version":"v1.1"})})
mux.HandleFunc("/v1/targets",func(w http.ResponseWriter,r *http.Request){if r.Method=="GET"{write(w,200,s.Targets());return};if r.Method!="POST"{method(w);return};var t model.Target;if err:=json.NewDecoder(r.Body).Decode(&t);err!=nil{bad(w,err);return};if err:=s.AddTarget(t);err!=nil{bad(w,err);return};write(w,201,t)})
mux.HandleFunc("/v1/leases",func(w http.ResponseWriter,r *http.Request){if r.Method!="POST"{method(w);return};var in struct{TargetID string `json:"target_id"`;TTLSeconds int `json:"ttl_seconds"`;Budget int `json:"budget"`};if json.NewDecoder(r.Body).Decode(&in)!=nil{http.Error(w,"invalid json",400);return};if in.TTLSeconds==0{in.TTLSeconds=300};if in.Budget==0{in.Budget=100};l,e:=s.NewLease(in.TargetID,time.Duration(in.TTLSeconds)*time.Second,in.Budget);if e!=nil{bad(w,e);return};write(w,201,l)})
mux.HandleFunc("/v1/leases/",func(w http.ResponseWriter,r *http.Request){p:=strings.TrimPrefix(r.URL.Path,"/v1/leases/");parts:=strings.Split(p,"/");if len(parts)<2{http.NotFound(w,r);return};id:=parts[0];if parts[1]=="revoke"&&r.Method=="POST"{if e:=s.RevokeLease(id);e!=nil{bad(w,e);return};write(w,200,map[string]bool{"revoked":true});return};if parts[1]=="events"{if r.Method=="GET"{write(w,200,s.Events(id));return};if r.Method=="POST"{var e model.Event;if json.NewDecoder(r.Body).Decode(&e)!=nil{http.Error(w,"invalid json",400);return};e.LeaseID=id;if e.URL!=""{t,ok:=s.GetTarget(mustLeaseTarget(s,id));if !ok||!store.OriginAllowed(t,e.URL){http.Error(w,"event origin outside target",403);return}};if err:=s.RecordEvent(e);err!=nil{bad(w,err);return};write(w,201,e);return}};http.NotFound(w,r)})
mux.HandleFunc("/v1/redact",func(w http.ResponseWriter,r *http.Request){if r.Method!="POST"{method(w);return};var in model.RedactRequest;if json.NewDecoder(r.Body).Decode(&in)!=nil{http.Error(w,"invalid json",400);return};text,t:=redaction.Redact(in.Text,in.Rules);write(w,200,model.RedactResponse{Text:text,Tokens:t})})
addr:=os.Getenv("BROKER_ADDR");if addr==""{addr=":8080"};log.Printf("broker-api listening on %s",addr);log.Fatal(http.ListenAndServe(addr,withCORS(mux)))}
func mustLeaseTarget(s *store.Store,id string)string{l,ok:=s.GetLease(id);if !ok{return ""};return l.TargetID}
func write(w http.ResponseWriter,code int,v any){w.Header().Set("content-type","application/json");w.WriteHeader(code);_=json.NewEncoder(w).Encode(v)}
func bad(w http.ResponseWriter,e error){http.Error(w,e.Error(),400)}
func method(w http.ResponseWriter){http.Error(w,"method not allowed",405)}
func withCORS(n http.Handler)http.Handler{return http.HandlerFunc(func(w http.ResponseWriter,r *http.Request){w.Header().Set("access-control-allow-origin","*");w.Header().Set("access-control-allow-methods","GET,POST,OPTIONS");w.Header().Set("access-control-allow-headers","content-type,authorization");if r.Method=="OPTIONS"{w.WriteHeader(204);return};n.ServeHTTP(w,r)})}
var _=strconv.Itoa
